services:
  db:
    image: postgres:15
    container_name: hs-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hsdev
      POSTGRES_PASSWORD: hsdev123
      POSTGRES_DB: hsdevdb
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hs-dev-api
    ports:
      - "3333:3333"
    command: sh -c "npx prisma migrate dev && npx prisma db seed && npm run dev"
    env_file:
      - .env
    depends_on:
      - db

      
