#Nome
name: Deploy Hipersenna-api

#Trigger do workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar comandos na VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 8822
          key: ${{ secrets.SSH_KEY }}
          debug: true 
          script: |
            powershell.exe -Command "
              cd C:\var\www\hipersenna-api;
              git pull;
              npm install;
              npm run build;
            "
